<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <xacro:include filename="inertial_macros.xacro" />
    <xacro:include filename="lidar.xacro" />

    <xacro:property name="base_mass" value="46.034" />
    <xacro:property name="wheel_mass" value="2.637" />
    <xacro:property name="wheel_thickness" value="0.05" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="chassis_length" value="0.6" />
    <xacro:property name="chassis_width" value="0.3" />
    <xacro:property name="chassis_height" value="0.15" />
    
   
    <!--   base of the robot -->
  <link name="base_link">
  </link>

    <!-- BASE LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="-0.2 0 0" rpy="0.0 0.0 0.0"/>
    </joint>
    <link name="base_footprint">
        <visual>
            <origin xyz="0.3 0 0.075"/>  <!--  changed y to 0.15 from 0 on 21dec -->
            <geometry>
                     <box size="0.6 0.3 0.15"/>       
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.3 0 0.075"/>
            <geometry>
                     <box size="0.6 0.3 0.15"/>       
            </geometry>
            <material name="white"/>
        </collision> 
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>   
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>




    <!-- right front wheel  -->
    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_front_wheel"/>
        <origin xyz="0.275 -0.190 0.05" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="right_front_wheel">
        <visual>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                <!-- <mesh filename="file://$(find ebot_description)/meshes/RWL.STL" /> -->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- left front wheel  -->
    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_front_wheel"/>
        <origin xyz="0.275 0.190 0.05" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_front_wheel">
        <visual>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                <!-- <mesh filename="file://$(find ebot_description)/meshes/RWL.STL" /> -->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_front_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>



    <!-- right back wheel  -->
    <joint name="right_back_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_back_wheel"/>
        <origin xyz="-0.075 -0.190 0.05" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="right_back_wheel">
        <visual>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                <!-- <mesh filename="file://$(find ebot_description)/meshes/RWL.STL" /> -->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_back_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- left back wheel  -->
    <joint name="left_back_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_back_wheel"/>
        <origin xyz="-0.075 0.190 0.05" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="left_back_wheel">
        <visual>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                <!-- <mesh filename="file://$(find ebot_description)/meshes/RWL.STL" /> -->
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
            <geometry>
                <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_back_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
  
    

</robot>